name: Github-Action

on:
  pull_request:
  push:
    branches: master

jobs:
  test:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - macOS-latest
          - windows-latest

        resolver:
          - nightly   # ghc-9.4 (as of writing)
          - lts       # ghc-9.2 (as of writing)
          - lts-20.11 # ghc-9.2
          - lts-19.33 # ghc-9.0
          - lts-18.28 # ghc-8.10
          - lts-16.31 # ghc-8.8
          - lts-12.26 # ghc-8.4

      fail-fast: false

    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v3
      - uses: freckle/stack-cache-action@v2
        with:
          prefix: ${{ matrix.runner }}/${{ matrix.resolver }}/

      - id: stack
        uses: ./
        with:
          stack-arguments: --resolver ${{ matrix.resolver }}

      - if: ${{ runner.os != 'windows' }}
        run: |
          [[ "${{ steps.stack.outputs.compiler }}" = "ghc-8.10.4" ]]
          [[ "${{ steps.stack.outputs.compiler-version }}" = "8.10.4" ]]

          # stack path | cut -d: -f1
          [[ -n "${{ steps.stack.outputs.snapshot-doc-root }}" ]]
          [[ -n "${{ steps.stack.outputs.local-doc-root }}" ]]
          [[ -n "${{ steps.stack.outputs.local-hoogle-root }}" ]]
          [[ -n "${{ steps.stack.outputs.stack-root }}" ]]
          [[ -n "${{ steps.stack.outputs.project-root }}" ]]
          [[ -n "${{ steps.stack.outputs.config-location }}" ]]
          [[ -n "${{ steps.stack.outputs.bin-path }}" ]]
          [[ -n "${{ steps.stack.outputs.programs }}" ]]
          [[ -n "${{ steps.stack.outputs.compiler-exe }}" ]]
          [[ -n "${{ steps.stack.outputs.compiler-bin }}" ]]
          [[ -n "${{ steps.stack.outputs.compiler-tools-bin }}" ]]
          [[ -n "${{ steps.stack.outputs.local-bin }}" ]]

          # Actually blank in default setup
          # [[ -n "${{ steps.stack.outputs.extra-include-dirs }}" ]]
          # [[ -n "${{ steps.stack.outputs.extra-library-dirs }}" ]]

          [[ -n "${{ steps.stack.outputs.snapshot-pkg-db }}" ]]
          [[ -n "${{ steps.stack.outputs.local-pkg-db }}" ]]
          [[ -n "${{ steps.stack.outputs.global-pkg-db }}" ]]
          [[ -n "${{ steps.stack.outputs.ghc-package-path }}" ]]
          [[ -n "${{ steps.stack.outputs.snapshot-install-root }}" ]]
          [[ -n "${{ steps.stack.outputs.local-install-root }}" ]]
          [[ -n "${{ steps.stack.outputs.dist-dir }}" ]]
          [[ -n "${{ steps.stack.outputs.local-hpc-root }}" ]]
          [[ -n "${{ steps.stack.outputs.local-bin-path }}" ]]
          [[ -n "${{ steps.stack.outputs.ghc-paths }}" ]]
