name: Less-Short-Github-Action

on:
  pull_request:
  push:
    branches: master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: freckle/stack-action@v3

      - id: stack
        uses: freckle/stack-action@v3
        with:
          stack-arguments: --copy-bins --coverage

      - uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ${{ steps.stack.outputs.local-hpc-root }}/index.html